sudo: required
language: node_js
node_js:
  - 'node'
  - '8'

services:
  - docker

install:
  - npm install

script:
  - npm run bundle
  - npm test

after_success:
  - source scripts/docker_push.sh
  - npm run coveralls

matrix:
  allow_failures:
    - after_success: scripts/docker_push.sh
